---
name: release
run-name: Publish the release to somewhere
on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
jobs:
  download-artifacts:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download the artifact from build workflow
        uses: actions/download-artifact@v4
        with:
          name: artifact
          run-id:
        run-id

  steps:
- uses: actions/download-artifact@v4
  with:
    name: Download artifacts from build workflow
    run-id:  ${{ github.event.workflow_run.id }}

  release-artifacts:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Upload to somewhere
        run: echo "We do the upload here"
